### ISSUE TITLE
Why pyobjus instead of pyobjc?

### ISSUE THREAD

**Issue by Congee** [rr-/screeninfo#12]
https://github.com/rr-/screeninfo/blob/a23473bc28e8da41cb7df53a89428d671b4d0168/screeninfo/screeninfo.py#L367

https://github.com/rr-/screeninfo/blob/a23473bc28e8da41cb7df53a89428d671b4d0168/screeninfo/screeninfo.py#L399
More, if you print the exception, users would know they should `pip install pyobjus`.

**Comment by rr-** [comment]
Because I don't have a Mac and this was contributed by someone else.
