### ISSUE TITLE
Access to monitor name, when available

### ISSUE THREAD

**Issue by Evidlo** [rr-/screeninfo#14]
Under Linux, monitors are assigned names like `VGA0`, `LVDS0`, `HDMI0`, `DVI-0`, etc.  It would be nice if these were accessible.

**Comment by rr-** [comment]
I pushed some commits on `master` branch, LMK if it works for you.

Please note that this feature needs XRandR, as Xinerama, the original library used by `screeninfo`, doesn't give access to monitor names. The original xinerama-based enumerator, which was named `x11`, was renamed to `xinerama`, whereas the new XRandR-based enumerator is available under `xrandr` name.

**Comment by Evidlo** [comment]
You should add `dataclasses` to `setup.py` for python3.6 support.

**Comment by rr-** [comment]
You should make a pull request.
