### ISSUE TITLE
Breaking Python 2.7

### ISSUE THREAD

**Issue by MDTech-us-MAN** [rr-/screeninfo#15]
The changes that were made a few hours ago, specifically common.py, break Python 2.7.

**Comment by rr-** [comment]
If you're using Python 2.7, you should be fine with using screeninfo 0.3.1.

**Comment by MDTech-us-MAN** [comment]
Maybe add a comment in the Readme about dropping Python 2 support that mention the last compatible version?
There are still too many massive projects stuck on 2.7, which will take a while to convert.
