### ISSUE TITLE
Is this broken on Windows 10?

### ISSUE THREAD

**Issue by TropicMike** [rr-/screeninfo#2]
I'm using screeninfo on Win7 with excellent results (thank you!!)

However, when I try to run it on either of my Win10 (Pro 64 bit if it matters) boxes, I get an empty list "[]" returned when I try to call get_monitors().

I don't know enough about the Win32 libs to debug what is going-on, so I come offering only a problem and no solution :(  Perhaps you can help?

Thanks!

**Comment by rr-** [comment]
Unfortunately I don't have Win 10 machine around these days. Are you using Cygwin or plain Python?

**Comment by TropicMike** [comment]
Hi!

I'm using straight Python (3.3.5 due to a version requirement) on all machines.

if I try to run the win32 command manually, I get a "FuncPtr" back.  Beyond that, I have no idea what the callback/etc. does.

>>> screeninfo.get_monitors()
[]


>>> import os
>>> import sys
>>> print(ctypes.windll.user32.EnumDisplayMonitors)
<_FuncPtr object at 0x00000000028F0458>


Thanks,
Mike

**Comment by TropicMike** [comment]
It looks like I can use win32api.EnumDisplayMonitors to get the data I need for my application, so that's a potential alternative to keep in-mind for anyone who comes across this post and is on Win10 for now.  Here's a simple example:

import win32api

monitors = win32api.EnumDisplayMonitors()
for i in monitors:
    (_,_,coords) = i
    (left, top, right, bottom) = coords
    print(right - left, bottom - top)

**Comment by TropicMike** [comment]
Hi!

I'm using straight Python (3.3.5 due to a version requirement) on all
machines.

if I try to run the win32 command manually, I get a "FuncPtr" back.  Beyond
that, I have no idea what the callback/etc. does.

>>> screeninfo.get_monitors()
[]


>>> import os
>>> import sys
>>> print(ctypes.windll.user32.EnumDisplayMonitors)
<_FuncPtr object at 0x00000000028F0458>


Thanks,
Mike

**Comment by rr-** [comment]
Works for me on Windows 10.

`cmd.exe`:

```console
Z:\src\maintained\screeninfo>"C:\Python35\python.exe" screeninfo/screeninfo.py
monitor(1680x1050+0+0)
monitor(1680x1050+1680+0)

Z:\src\maintained\screeninfo>"C:\Python35\python.exe" --version
Python 3.5.2
```

Cygwin:

```console
rr-@machine:/cygdrive/z/src/maintained/screeninfo$ python3 screeninfo/screeninfo.py
monitor(1680x1050+0+0)
monitor(1680x1050+1680+0)
rr-@machine:/cygdrive/z/src/maintained/screeninfo$ python3 --version
Python 3.4.5
rr-@machine:/cygdrive/z/src/maintained/screeninfo$ uname -a
CYGWIN_NT-10.0-WOW machine 2.6.1(0.305/5/3) 2016-12-16 11:50 i686 Cygwin
```
