### ISSUE TITLE
Wrong resolution on Windows when scaled

### ISSUE THREAD

**Issue by benshep** [rr-/screeninfo#26]
I have two monitors on a Windows 10 laptop. The inbuilt display is set to 125% scale in Settings - see pic. But screeninfo gives the wrong resolution - it scales it by 125% and returns 1536x864 instead of 1920x1080. Can I have it return an unscaled resolution please?

![image](https://user-images.githubusercontent.com/5038790/77336625-b4071c00-6d1f-11ea-85b8-b9274b9766d6.png)

**Comment by benshep** [comment]
An update on this. I was using an old version of screeninfo that didn't have the DPI aware stuff. I updated it and it still doesn't quite work as I want.

My monitors are 

1. 1920x1080, scaled to 125%
2. 1920x1080, scaled to 100%

They are side-by-side i.e. [1][2].

The newest version of screeninfo returns

    [Monitor(x=0, y=0, width=1920, height=1080, width_mm=309, height_mm=173, name='\\\\.\\DISPLAY1'), 
     Monitor(x=2400, y=0, width=2400, height=1350, width_mm=510, height_mm=287, name='\\\\.\\DISPLAY2')]

So monitor 2 is getting scaled up - I don't think this is right. (My use case: producing a large wallpaper image that goes across both monitors. Currently it looks correct on monitor 2 but it doesn't scale correctly on monitor 1.)

**Comment by hhannine** [comment]
Do I read your output correctly that after updating you're getting a too large resolution on the larger of the 2 of your displays, which is using 100% scaling? Quite peculiar if so.

**Comment by hhannine** [comment]
This issue might be explained by this SO post: https://stackoverflow.com/a/44422362

**Comment by benshep** [comment]
The SO post gave the answer. To get screeninfo to report the resolutions correctly, I had to do

    import ctypes
    ctypes.windll.shcore.SetProcessDpiAwareness(2)

before querying `get_monitors`. When I did, the output was the expected:

    [Monitor(x=0, y=0, width=1920, height=1080, width_mm=309, height_mm=173, name='\\\\.\\DISPLAY1'), 
     Monitor(x=1920, y=0, width=1920, height=1080, width_mm=510, height_mm=287, name='\\\\.\\DISPLAY2')]

Thanks a lot! I'll leave it up to you whether you close the issue or not - I have an effective workaround so I'm happy, but I don't know whether you want to put it into screeninfo somewhere (I guess it might have unintended consequences for others).

**Comment by hhannine** [comment]
I'd like to see this resolved permanently in the package itself since the true resolution is the intended and expected output. It would seem that the solution is different for W7&older than on Win8+ which is a bit shame.

Since you've got the hardware to test the implementation, would you mind writing a patch that replaces the current SetProcessDPIAware call on Win8 and Win10 machines with your solution?

**Comment by rr-** [comment]
Fix by @benshep is available on master and on PyPI as 0.6.3.
