### ISSUE TITLE
Installation on Windows fails due to Pyobjus

### ISSUE THREAD

**Issue by robot-love** [rr-/screeninfo#40]
Tried installing this package using Poetry, and I keep getting the following error:

```
[NotADirectoryError]
[WinError 267] The directory name is invalid: 'C:\\Users\\sghavam\\AppData\\Local\\Temp\\tmp56okfexg\\unpacked\\pyobjus-1.1.0\\objc_classes\\aux'
```

Folders named `aux` (among others) are not permitted on Windows platforms so the installation fails.

**Comment by rr-** [comment]
Looks like the problem is outside of this repository; pyobjus is marked to be installed only on darwin (osx) platforms.
