### ISSUE TITLE
Fall back on Windows if X11 fails

### ISSUE THREAD

**Issue by benshep** [rr-/screeninfo#5]
I have Windows 7, and I occasionally use an X11 client (MobaXTerm). I think this has resulted in my `DISPLAY` environment variable being set. But I don't have a running X server, so screeninfo fails when it tries to find it (ImportError: Could not load X11). The 'standard' ctypes method works fine. Could you either:

- Re-order the detection so that it uses the `MonitorEnumeratorWindows` class in preference to `MonitorEnumeratorX11`
- Add a parameter to `get_monitors` to force a particular platform
- Fall back to `MonitorEnumeratorWindows` when X11 can't be loaded (perhaps by adding more cleverness to the detect code).

The last one would be my preference, but the other two would be much simpler to implement!

Thanks

Ben

**Comment by rr-** [comment]
Sure, I'll implement the suggestion 2 and 3

**Comment by benshep** [comment]
Thanks!

**Comment by rr-** [comment]
Done in recent commits, released as `0.3` on PyPI.
