### ISSUE TITLE
Fails on Linux under cron

### ISSUE THREAD

**Issue by benshep** [rr-/screeninfo#6]
I'm using this in a Python script that changes the wallpaper. I've got this set up as a cron job so that it runs on a timer. But it fails with a "Could not open display" exception. Any idea what I should do to make it work?

**Comment by rr-** [comment]
For a quick solution, please try running it like this: `DISPLAY=:0.0 the-script`
I'll try to look for a solution that allows one to query the monitors w/o XRandR.

**Comment by benshep** [comment]
Oh yes, that works. Thanks a lot!

**Comment by rr-** [comment]
I've also added an experimental DRM driver, which should work from Linux cron. I can't promise it'll work with every graphic card and I haven't had the chance to test it with dual head setup either, however, it seems to work okay on my notebook with an Intel card.

**Comment by benshep** [comment]
Sorry, only just got around to trying the DRM driver.

On my laptop ([Toshiba Portege R600-11B](http://www.toshiba.co.uk/discontinued-products/portege-r600-11b/)), if I do `mons = screeninfo.get_monitors('drm')`, it just drops out of Python without giving an error message. Any thoughts? Can I diagnose this?

**Comment by rr-** [comment]
Try debugging the code with `pdb`

**Comment by benshep** [comment]
Done; it was throwing an `OSError` on closing the file descriptor, because you'd put `os.close(card_no)` instead of `os.close(fd)`. I don't know why I didn't see that error without using `pdb` though. Anyway, sent you a PR: #7

**Comment by rr-** [comment]
Thanks, merged.
