### ISSUE TITLE
save width and height to a variable

### ISSUE THREAD

**Issue by Impre-visible** [rr-/screeninfo#66]
how to save the width and the height of all the screen to a variable ? 1 variable for each screen

**Comment by rr-** [comment]
I don't understand what you're asking for.

**Comment by Impre-visible** [comment]
if i do that :
```py

for m in get_monitors():
    print(str(m))
```
i have all the info, know i just want to get the width in m and the height in m

**Comment by rr-** [comment]
`print(m.width, m.height, m.x, m.y)`
for details consult screeninfo/common.py.

**Comment by Impre-visible** [comment]
thanks
