### ISSUE TITLE
Behavior of get_monitors()

### ISSUE THREAD

**Issue by Aleadinglight** [rr-/screeninfo#9]
Hello,
I see that the example showing multiple monitors but doesn't specify any differences between them. So I would like to ask: If there are **two monitors both available at the same** time but **only one is active**,  can we get that specific monitor?

**Comment by rr-** [comment]
I don't understand the question, active = powered on? Or do you mean set as primary?

**Comment by Aleadinglight** [comment]
Oh, I mean set as primary.

**Comment by rr-** [comment]
I haven't considered this use case; this information isn't offered by the API. Chances are that the enumeration procedure lists the primary monitor as the first one, but that's up to the OS-specific API side effects.
